### ISSUE TITLE
Would docker-based builds for MIPS, s390x, and ppc64 in CI be useful?

### ISSUE THREAD

**Issue by jeking3** [boostorg/context#108]
I recently added a ppc64 multiarch build job to boostorg/uuid to prove out some endian issues.  I see a few architecture related issues open and resolved here; wondering if building in simulated architectures and running all the tests would be useful?  Thise multiarch docker images run 10-20 times slower so there could be some issues with builds timing out on GitHub, but I found it very useful in making sure things were working on those architectures.

**Comment by olk** [comment]
in general it's a good idea - s390x is under development, but MIPS, PPC32/64 and RISC-V should work.
