### ISSUE TITLE
Add support for ThreadSanitizer (TSAN)

### ISSUE THREAD

**Issue by alokpr** [boostorg/context#124]
Clang recently added fiber support: https://reviews.llvm.org/D54889

Please consider adding necessary instrumentation so that boost::Context can be used with TSAN.

**Comment by lenerd** [comment]
TSan support in Boost.Context/Fiber would be great.

I tried to do this myself but so far I have not been successful (cf. https://github.com/boostorg/fiber/issues/214#issuecomment-538018484_).

**Comment by olk** [comment]
closing because of no progress/no patch provided
