### ISSUE TITLE
Whole Program Optimization /GL on windows

### ISSUE THREAD

**Issue by Trigve** [boostorg/context#126]
Hi,
in the documentation, there is this text
`Windows using fcontext_t: turn off global program optimization (/GL) and change /EHsc (compiler assumes that functions declared as extern "C" never throw a C++ exception) to /EHs (tells compiler assumes that functions declared as extern "C" may throw an exception). `

I've used context (with the /GL and /EHsc) as part of boost.coroutine and didn't experienced any crash or whatsoever.
Is this still valid (mainly the /GL)?
I'm asking because I'm going to migrate to the boost.fibers, where there is this notice too (because it is using context) and want to be sure everything will be smooth.

**Comment by olk** [comment]
I don't use Windows as development platform - to switch off /GL and /EHsc was reported by some users.

**Comment by Trigve** [comment]
Ok, I'll try and if will encounter some crashes I'll reply back.

**Comment by olk** [comment]
no reply
