### ISSUE TITLE
Make make_fcontext jump_fcontext as public api

### ISSUE THREAD

**Issue by Klayflash** [boostorg/context#134]
Hello.

Currently I use make_fcontext and jump_fcontext as replacement of windows api: CreateFiberEx, SwitchToFiber. It is required to port old code. Please make the functions public.

I need only context switching capabilities. I think that this ability should be exported this library separately.

Also it will be harder to use private functions after new C++ standard modules will arrive.

**Comment by olk** [comment]
It is not a good idea to make these functions part of the public API.
The public API prevents accidental resuming an already running fiber, manages lifetime of the stack etc.

**Comment by Klayflash** [comment]
How to use boost library to port old code from CreateFiberEx, SwitchToFiber and GetCurrentFiber?
Task: replace winapi code to make it portable.

**Comment by olk** [comment]
use boost::context:.fiber instead - of course you have to adopt your code

**Comment by Klayflash** [comment]
boost::context:.fiber does not provide GetCurrentFiber. So code adaptation will be costly.

**Comment by olk** [comment]
GetCurrentFiber() is dangerous ... you could try to destroy the current fiber by accident
boost.context's fiber tries to prevent such problems

**Comment by Klayflash** [comment]
In my case GetCurrentFiber is not dangerous because of it is already debugged and long time running on end user. I just want make my code more portable by replacing functions calls.

I sure this applied is not only for me. So this functionality will be useful for other people.
