### ISSUE TITLE
[1.73.0] i686-w64-mingw32/bin/ld: cannot export _jump_fcontext: symbol not found

### ISSUE THREAD

**Issue by jschueller** [boostorg/context#136]
the 1.73 version fails to build on the 32 bits variant (but succeeds on 64bits) of mingw with the following error:
```
gcc.link.dll bin.v2/libs/context/build/gcc-mingw64/release/binary-format-pe/target-os-windows/threading-multi/visibility-hidden/libboost_context.dll.a

    "i686-w64-mingw32-g++"   "-Wl,--out-implib,bin.v2/libs/context/build/gcc-mingw64/release/binary-format-pe/target-os-windows/threading-multi/visibility-hidden/libboost_context.dll.a" -o "bin.v2/libs/context/build/gcc-mingw64/release/binary-format-pe/target-os-windows/threading-multi/visibility-hidden/libboost_context.dll" -Wl,-h -Wl,libboost_context.dll -shared -Wl,--start-group "bin.v2/libs/context/build/gcc-mingw64/release/binary-format-pe/target-os-windows/threading-multi/visibility-hidden/asm/make_i386_ms_pe_gas.o" "bin.v2/libs/context/build/gcc-mingw64/release/binary-format-pe/target-os-windows/threading-multi/visibility-hidden/asm/jump_i386_ms_pe_gas.o" "bin.v2/libs/context/build/gcc-mingw64/release/binary-format-pe/target-os-windows/threading-multi/visibility-hidden/asm/ontop_i386_ms_pe_gas.o" "bin.v2/libs/context/build/gcc-mingw64/release/binary-format-pe/target-os-windows/threading-multi/visibility-hidden/dummy.o" "bin.v2/libs/context/build/gcc-mingw64/release/binary-format-pe/target-os-windows/threading-multi/visibility-hidden/windows/stack_traits.o"  -Wl,-Bstatic  -Wl,-Bdynamic  -Wl,--end-group -m32 -mthreads -fvisibility=hidden -fvisibility-inlines-hidden -march=i686 -Wl,-O1,--sort-common,--as-needed -fstack-protector

/usr/lib/gcc/i686-w64-mingw32/9.3.0/../../../../i686-w64-mingw32/bin/ld: cannot export _jump_fcontext: symbol not found
```

The faulty commit is https://github.com/boostorg/context/commit/85783e8cbba03804e13b3d314112df6b089ed2c0 from #127
Maybe fixing for LLVM's ld resulted in breaking the build with GNU's ld.

cc @ericastor

**Comment by mabrarov** [comment]
I have the same issue with the latest **release** version of Boost - 1.73.0 - and MinGW 7.3.0 32 bits on Windows Server 2019 (mcr.microsoft.com/windows/servercore:ltsc2019 docker image):

```
gcc.link.dll bin.v2\libs\context\build\gcc-7.3.0\debug\threading-multi\visibility-hidden\libboost_context-mgw7-mt-d-x32-1_73.dll.a
C:/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-mingw32/bin/ld.exe: Cannot export _jump_fcontext: symbol not found
C:/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-mingw32/bin/ld.exe: Cannot export _make_fcontext: symbol not found
C:/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/../../../../i686-w64-mingw32/bin/ld.exe: Cannot export _ontop_fcontext: symbol not found
collect2.exe: error: ld returned 1 exit status
```

**Comment by ericastor** [comment]
It sounds like the issue here is that in 32-bit MinGW, the GNU assembler is prepending a `_` onto the symbols defined in assembler files - which is why they were getting exported correctly before - and this isn't the case with LLVM's assembler. One of GNU and LLVM has a bug here. Since there's no actual reference for GNU-style assembly for Windows, the question is: which is a better idea?

Personally, I think silently changing the name of a symbol is bad behavior for an assembler, which is supposed to do exactly as they're told. Maybe this should be filed as a bug against GNU's as?

In the meantime... it seems like a shame, but do we need to fork these assembly files into GNU vs. LLVM to keep this working?

**Comment by mabrarov** [comment]
Regarding shame - I checked [1.73.0 release notes](https://www.boost.org/users/history/version_1_73_0.html):

> Compilers Tested
> 
> Boost's primary test compilers are: 
> ...
> Windows:
> ...
> * GCC, C++17: 7.1.0, 7.2.0, **7.3.0**

And I'm curios what combination of build flags / platforms was tested and how was it tested? Maybe I just miss some build (Boost.Build) flag which makes MinGW 7.3.0 exporting symbols on 32-bit platform correctly?

**Comment by jschueller** [comment]
Maybe they just test x86_64

**Comment by jschueller** [comment]
@ericastor  I think the gnu assembler was there first ;)

**Comment by ericastor** [comment]
@jschueller Doesn't mean it can't have bugs... ;)

**Comment by mabrarov** [comment]
I found that Boost 1.73.0 libraries built with MinGW 7.3.0 have mgw7 suffix instead of mgw73 suffix comparing to Boost 1.72.0, e.g. libboost_atomic-**mgw7**-mt-d-x64-1_73.a instead of libboost_atomic-**mgw73**-mt-d-x64-1_72.a. This difference breaks FindBoost module of CMake 3.17.2 and it cannot find built Boost 1.73.0 libraries.

**Comment by mabrarov** [comment]
Still an issue with MinGW 7.3.0 x86 build of Boost 1.74.0

**Comment by ericastor** [comment]
Apologies; I'm still going to suggest that this should be filed as a bug against either gas or LLVM/clang. It seems likely this should at least be a configurable linker behavior.

Alternatively, someone could fork the assembly files into a MinGW and non-MinGW version.

**Comment by mati865** [comment]
Both Binutils and LLVM in MinGW mode will prepend `_` to 32-bit symbols. This is sort of a "convention" for that target.

**Comment by jschueller** [comment]
so llvm would be faulty here ?

**Comment by jschueller** [comment]
the question would be how to differentiate regular lld from lld in mingw mode if splitting the assembly files is in order

**Comment by mati865** [comment]
Those files appear to be meant for MinGW only, so using them without MinGW linker sounds like asking for troubles already.

**Comment by jschueller** [comment]
so we would need a new jump_i386_ms_pe_lld.asm ?

**Comment by mati865** [comment]
I don't think so, this looks to me as user error(using wrong linker).
MSVC and MinGW have different ABIs so one has to always use correct linker. The only way to mix them is through DLLs, otherwise it's asking for problems.

**Comment by jschueller** [comment]
so it should have been masm, not gas ?

**Comment by ericastor** [comment]
Hm. This has actually gotten interesting... because I can say from quite a bit of experience that this was actually *working*. Removing this is breaking a consuming piece of software.

**Comment by mati865** [comment]
@ericastor GCC/Binutils supports only MinGW mode but Clang/LLVM do support both MinGW and MSVC modes.
#127 broke MinGW mode so it was reverted by various parties:
- https://github.com/msys2/MINGW-packages/pull/6504/files#diff-031b04b8132e93b1279e644ca2efadcf
- https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mingw-w64-boost&id=b06f6e147ecd0415999742395abbd3d34c88a01f#n31
- https://src.fedoraproject.org/rpms/mingw-boost/blob/c40a70c9b75fba763e8bb288f03f8664d0d64ea3/f/boost-mingw.patch#_107

Looking by the name `*_i386_ms_pe_gas.asm` sound like they are MinGW mode for GNU assembler and `*_i386_ms_pe_masm.asm` are meant for Microsoft's assembler.

**Comment by ericastor** [comment]
@mati865 Fair enough - but I do have a legitimate use case. We compile with Clang targeting MSVC mode - and do not use Microsoft's assembler.

I'm currently working on getting MASM support into Clang, but it's not there yet; instead, it's capable of using GNU-style assembler to target MSVC. As mentioned, this works quite well. Can we consider using a define from the build files to distinguish these cases instead?

**Comment by mati865** [comment]
@ericastor sounds fair. In that case leaving `*gas` for MinGW and creating new files for Clang targeting MSVC sounds like logical thing to do.
