### ISSUE TITLE
mingw64: error: No best alternative for libs/context/build/asm_sources

### ISSUE THREAD

**Issue by jschueller** [boostorg/context#137]
when I use mingw (gcc 9.3) from Linux context throw this warning at configure time:
error: No best alternative for libs/context/build/asm_sources
and fails to build later with some undefined references

my user-config.jam looks like this:
using gcc : mingw64 : x86_64-w64-mingw32-g++

a workaround is to patch in build/Jamfile.v2 default_binary_format and default_abi to return pe and ms

I tried latest 1.73.0rc1

**Comment by olk** [comment]
Error message means that boost.build can not determine which asm file has to be choosen.
please provide a patch

**Comment by jschueller** [comment]
yes, the root of all this is that the abi and binary format are incorrect.

**Comment by olk** [comment]
closing because no progress
