### ISSUE TITLE
ARM64 compiler error: No best alternative for libs/context/build/asm_sources

### ISSUE THREAD

**Issue by sbrahul** [boostorg/context#139]
Hi,

I am trying to build boost 1.72 with arm 64 bit compiler. I am seeing the error:
No best alternative for libs/context/build/asm_sources
Although, after getting this error, compilation looks to succeed, but I am not sure if it did properly or not.

I have this line in the project-config.jam:
using gcc : arm : aarch64-fsl-linux-g++ --sysroot=/sysroots/aarch64-fsl-linux ;

After running b2, I get the following output:
./b2 toolset=gcc-arm
Performing configuration checks

    - default address-model    : 64-bit
    - default architecture     : arm

Building the Boost C++ Libraries.

error: No best alternative for libs/context/build/asm_sources
    next alternative: required properties: <abi>aapcs <address-model>32
<architecture>arm <binary-format>elf <threading>multi <toolset>clang
        not matched
    next alternative: required properties: <abi>aapcs <address-model>32
<architecture>arm <binary-format>elf <threading>multi <toolset>gcc
        not matched
    next alternative: required properties: <abi>aapcs <address-model>32
<architecture>arm <binary-format>elf <threading>multi <toolset>qcc
        not matched
    next alternative: required properties: <abi>aapcs <address-model>32
<architecture>arm <binary-format>mach-o <threading>multi <toolset>clang
        not matched
    next alternative: required properties: <abi>aapcs <address-model>32
<architecture>arm <binary-format>mach-o <threading>multi <toolset>darwin
        not matched
    next alternative: required properties: <abi>aapcs <address-model>32
<architecture>arm <binary-format>pe <threading>multi <toolset>msvc
        not matched
    next alternative: required properties: <abi>aapcs <address-model>64
<architecture>arm <binary-format>elf <threading>multi <toolset>clang
        not matched
    next alternative: required properties: <abi>aapcs <address-model>64
<architecture>arm <binary-format>elf <threading>multi <toolset>gcc
        not matched
    next alternative: required properties: <abi>aapcs <address-model>64
<architecture>arm <binary-format>mach-o <threading>multi <toolset>clang
        not matched
    next alternative: required properties: <abi>aapcs <address-model>64
<architecture>arm <binary-format>mach-o <threading>multi <toolset>darwin
        not matched
...

**Comment by jschueller** [comment]
It's a bit similar to https://github.com/boostorg/context/issues/137

**Comment by olk** [comment]
I guess that gcc-arm will not match the toolset property.

**Comment by sbrahul** [comment]
> I guess that gcc-arm will not match the toolset property.

I actually used gcc-arm as per the suggestion of the boost documentation page (although slightly older):
https://www.boost.org/doc/libs/1_64_0/doc/html/bbv2/tasks.html

The compiler I am using is gcc 9.2.0.

**Comment by olk** [comment]
I guess you have to specify the abi=aapcs64 and the binary-format=elf at command line.

**Comment by olk** [comment]
any update? may I close this issue

**Comment by lukaszkulas** [comment]
I had the same issue and after setting abi=aapcs64 and the binary-format=elf, I'm getting this:

![image](https://user-images.githubusercontent.com/112875784/205126161-70d0b417-46f2-459d-9627-588d95ca38c6.png)

@olk , do you know how to fix it?

**Comment by brechtsanders** [comment]
I'm also getting `error: No best alternative for libs/context/build/asm_sources` when building for Windows on ARM 64 (aarch64-w64-mingw32).

**Comment by moshev** [comment]
I ran into this issue as well and solved it by simply specifying everything:
`./b2 abi=aapcs address-model=64 architecture=arm binary-format=elf <rest of options>`

**Comment by brechtsanders** [comment]
@moshev `binary-format=elf` doesn't sound right for Windows on ARM as it uses COFF/PE, not ELF.

**Comment by moshev** [comment]
@brechtsanders I was compiling for Linux (and AFAIU so is the OP), so ELF is the right option for me. Of course if you're compiling for Windows, use the correct format for it.

**Comment by brechtsanders** [comment]
@moshev Ok. I suppose I also need to stick with `abi=ms` then instead of `abi=aapcs`.

**Comment by cryptozoidberg** [comment]
@brechtsanders did you ever solved this issue? I'm also on Windows Arm64, facing the same issue. Any suggestions would be appreciated!

**Comment by brechtsanders** [comment]
My build recipe is at https://github.com/brechtsanders/winlibs_recipes/blob/main/recipes/boost.winlib

Basically for boost 1.82.0 I used `--without-coroutine --without-context context-impl=winfib` for the aarch64 Windows on ARM platform.

For 1.84.0 I use CMake (+Ninja) to build using the following flags `-DBOOST_CONTEXT_IMPLEMENTATION:STRING=winfib -DBOOST_CONTEXT_ABI:STRING=ms` but unfortunately the shared build still gives me errors.

**Comment by brechtsanders** [comment]
Yes, I was able to build 1.84.0 static libraries on Windows on ARM.
