### ISSUE TITLE
Can't compile libs/context/src/asm/make_arm64_aapcs_macho_gas.S

### ISSUE THREAD

**Issue by gdochev** [boostorg/context#14]
Hi, I am trying to cross-compile the context library in 1.58 targeting iOS on an OSX host. The library builds fine for arm, but not for the newly introduced arm64. When running with:

    ./bjam                                                                               
        -j8                                                                                 
        --build-dir=iphone-build                                                
        --stagedir=iphone-build/stage                                      
        --prefix=$PREFIXDIR                                                  
        --toolset=darwin-${IPHONE_SDKVERSION}~iphone 
        toolset=darwin                                                             
        architecture=arm                                                         
        target-os=iphone                                                          
        address-model=64                                                       
        binary-format=mach-o                                                  
        abi=aapcs                                                                     
        macosx-version=iphone-${IPHONE_SDKVERSION}  
        define=_LITTLE_ENDIAN                                            
        link=static                                                                     
        threading=multi                                                            
        stage
 
I get a lot of those:

libs/context/src/asm/make_arm64_aapcs_macho_gas.S:54:21: error: unexpected token in argument list
    ; shift address in x0 (allocated stack) to lower 16 byte boundary
                    ^
libs/context/src/asm/make_arm64_aapcs_macho_gas.S:55:17: error: unexpected token in operand
    and x0, x0, ~0xF
                ^
libs/context/src/asm/make_arm64_aapcs_macho_gas.S:57:21: error: unexpected token in argument list
    ; reserve space for context-data on context-stack
                    ^
libs/context/src/asm/make_arm64_aapcs_macho_gas.S:58:9: error: invalid operand for instruction
    sub x0, x0, #0xb0
        ^
and so on...

And last but not least, thank you for this great library. Keep up the good work!

**Comment by gdochev** [comment]
My user-config.jam looks like this:

using darwin : 8.3~iphone
: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch arm64 -fvisibility=hidden -fvisibility-inlines-hidden -DBOOST_AC_USE_PTHREADS -DBOOST_SP_USE_PTHREADS -std=c++11 -stdlib=libc++
: <striper> <root>/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer
: <architecture>arm <target-os>iphone
;
using darwin : 8.3~iphonesim
: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch i386 -arch x86_64 -fvisibility=hidden -fvisibility-inlines-hidden -DBOOST_AC_USE_PTHREADS -DBOOST_SP_USE_PTHREADS -std=c++11 -stdlib=libc++
: <striper> <root>/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer
: <architecture>x86 <target-os>iphone
;

**Comment by olk** [comment]
the code was reported to be working - strange

**Comment by olk** [comment]
see - https://github.com/boostorg/context/pull/5

**Comment by gdochev** [comment]
Hi Oliver, thank you for the quick response. I am no expert in arm or clang so I am mostly guessing here but it looks as though the assembly syntax in make_arm64_aapcs_macho_gas.S may not be digestible by the integrated arm assembler in clang (https://wiki.libav.org/Tools/gas-preprocessor)

**Comment by gdochev** [comment]
Hi Oliver, do you have any updates on this?

**Comment by gdochev** [comment]
The issue has been resolved in 1.60.

**Comment by olk** [comment]
I don't own an ARM64 running on iOS - I've merged suggested patches as you see here
https://github.com/boostorg/context/pull/5.

**Comment by olk** [comment]
should work now

**Comment by neptunezx** [comment]
有别的大神说swoole编译的时候需要正确的选择协程汇编文件，需要修改config.m4等文件。用以下patch文件修改源码应该可以
`--- config.m4.orig	2021-01-15 15:45:57.000000000 +0800
+++ config.m4	2021-01-15 15:46:57.000000000 +0800
@@ -622,13 +622,7 @@
     )
 
     if test "$SW_OS" = "MAC"; then
-        if test "$SW_CPU" = "arm"; then
-            SW_CONTEXT_ASM_FILE="arm_aapcs_macho_gas.S"
-        elif test "$SW_CPU" = "arm64"; then
-            SW_CONTEXT_ASM_FILE="arm64_aapcs_macho_gas.S"
-        else
-            SW_CONTEXT_ASM_FILE="combined_sysv_macho_gas.S"
-        fi
+        SW_CONTEXT_ASM_FILE="combined_sysv_macho_gas.S"
     elif test "$SW_CPU" = "x86_64"; then
         if test "$SW_OS" = "LINUX"; then
             SW_CONTEXT_ASM_FILE="x86_64_sysv_elf_gas.S"
--- thirdparty/boost/asm/jump_combined_sysv_macho_gas.S.orig	2020-11-26 21:02:33.000000000 -0600
+++ thirdparty/boost/asm/jump_combined_sysv_macho_gas.S	2020-12-17 01:25:22.000000000 -0600
@@ -15,6 +15,10 @@
     #include "jump_ppc32_sysv_macho_gas.S"
 #elif defined(__ppc64__)
     #include "jump_ppc64_sysv_macho_gas.S"
+#elif defined(__arm__)
+    #include "jump_arm_aapcs_macho_gas.S"
+#elif defined(__arm64__)
+    #include "jump_arm64_aapcs_macho_gas.S"
 #else
     #error "No arch's"
 #endif
--- thirdparty/boost/asm/make_combined_sysv_macho_gas.S.orig	2020-11-26 21:02:33.000000000 -0600
+++ thirdparty/boost/asm/make_combined_sysv_macho_gas.S	2020-12-17 01:25:22.000000000 -0600
@@ -15,6 +15,10 @@
     #include "make_ppc32_sysv_macho_gas.S"
 #elif defined(__ppc64__)
     #include "make_ppc64_sysv_macho_gas.S"
+#elif defined(__arm__)
+    #include "make_arm_aapcs_macho_gas.S"
+#elif defined(__arm64__)
+    #include "make_arm64_aapcs_macho_gas.S"
 #else
     #error "No arch's"
 #endif`
参考 https://github.com/swoole/swoole-src/issues/3968
