### ISSUE TITLE
Support for macOS / ARM

### ISSUE THREAD

**Issue by dixlorenz** [boostorg/context#153]
What are your plans for supporting Apple Silicon?

**Comment by olk** [comment]
I've no access to Apple systems but you are welcome to provide a patch for macOS/ARM.

**Comment by dixlorenz** [comment]
Unfortunately, I wouldn't even know where to start. From my little understanding "it" (whatever that even is) should be the same as iOS. I'd be happy to help or test something.

**Comment by dixlorenz** [comment]
On my ARM MacBookPro I tried building boost as usual, just squeezing arch=arm64 everywhere; I didn't mess around with BOOST_USE_UCONTEXT or context-impl=ucontext at all. Boost built without problems I did see, my programs build, they are native and they run (using boost/fiber, not boost/context directly). A breakpoint set in fiber_entry (in context/fiber_fcontext.hpp) was hit, as far as I can tell it does use fcontext and not fall back to ucontext (I don't know if that could even happen). After a few hours of testing and running I want to say it works; there is one rare crash that I can't explain yet, working on it.

There might be a bug somewhere, but *AFAICT* it basically works. The build system for boost definitely needs updating, but boost/context and boost/fiber seem to be just missing updated documentation.

**Comment by olk** [comment]
ty for the information

**Comment by olk** [comment]
Do you use 32bit or 64bit  ARM?

**Comment by dixlorenz** [comment]
64 bit; I don't think macOS ARM 32 even exists

**Comment by olk** [comment]
documentation has been updated, ty
