### ISSUE TITLE
No downsides to `BOOST_USE_VALGRIND` documented?

### ISSUE THREAD

**Issue by alex-weej** [boostorg/context#158]
We've started using cooperative multitasking via Boost.Context but still need to use Valgrind. [The documentation for BOOST_USE_VALGRIND](https://www.boost.org/doc/libs/1_75_0/libs/context/doc/html/context/stack/valgrind.html) doesn't really mention any downsides of enabling this build and configuration option. I figure there must be some, otherwise it'd be on by default.

What are the downsides? Is there runtime overhead? Is it just not particularly well tested?

Thanks

**Comment by olk** [comment]
runtime overhead because additional code must be compiled in
usually you use valgrind aware code for inspecting bugs
