### ISSUE TITLE
Incorrect circle example for callcc

### ISSUE THREAD

**Issue by airstone42** [boostorg/context#176]
https://github.com/boostorg/context/blob/eb7c04713220ed9d3b56d3ea7a5d562a8942568b/example/callcc/circle.cpp#L21

It failed to compile as ```resume()``` was rvalue-ref qualified.

https://github.com/boostorg/context/blob/eb7c04713220ed9d3b56d3ea7a5d562a8942568b/example/callcc/circle.cpp#L11

It seems that this example was supposed to use ```callcc``` while it uses ```fiber``` now, which duplicates with [example/fiber/circle.cpp](https://github.com/boostorg/context/blob/develop/example/fiber/circle.cpp).

**Comment by olk** [comment]
ty, fixed
