### ISSUE TITLE
`binary-format` and `abi` detection does not support cross-compilation, nor multiarch

### ISSUE THREAD

**Issue by Kojoley** [boostorg/context#193]
Values for `binary-format` and `abi` are calculated using information about host, not the target:
https://github.com/boostorg/context/blob/83f998828c377ebd27d32455154f1f9cebf09b93/build/Jamfile.v2#L57-L65
https://github.com/boostorg/context/blob/83f998828c377ebd27d32455154f1f9cebf09b93/build/Jamfile.v2#L77-L86

The actual user was hit by this https://github.com/bfgroup/b2/issues/105#issuecomment-996115240

The logic also will yield incorrect results where a compiler is producing multiarch binaries, for example on apple clang it should at the same time deduce both `x86` and `arm` for `<architecture>`, and `sysv` and `aapcs` for `<abi>`.

**Comment by olk** [comment]
Support must be implemented inside boost.build

**Comment by Kojoley** [comment]
Cross compilation is implemented for some toolsets in B2 already, the mentioned code above which is not compatible with cross compilation is in Context.

**Comment by olk** [comment]
Boost.Build does not detect the ABI and BIANRY_FORMAT for which the code has to be compiled.
The only way is that you override it at command line with for instance `abi=ARM binary_format=ELF`
