### ISSUE TITLE
Cannot properly build boost for mips n64 - Boost.Context update breaks support

### ISSUE THREAD

**Issue by ClaymorePT** [boostorg/context#195]
Hello!

It seems that with the update from 1.77 to 1.78, Boost.Context mips support has unified all mips supported architectures, changing the target name `mips1` to `mips`. This work was not done for Boost build configuration and Boost.Atomic.

This issue was discovered with the Boost library update in OpenWRT done here https://github.com/openwrt/packages/pull/17512 where the issue was analysed and resolved for OpenWRT.

**Comment by olk** [comment]
should work now

**Comment by ClaymorePT** [comment]
Confirmed!
