### ISSUE TITLE
Wrong address-model and abi detection for x32 architecture?

### ISSUE THREAD

**Issue by bigon** [boostorg/context#200]
Hello,

In https://github.com/boostorg/context/blob/develop/build/Jamfile.v2 I see that the `<address-model>` for the x32 architecture is set to 64bits

But the point of x32 is to use 32bits pointers, isn't it?

If you look on debian [build logs](https://buildd.debian.org/status/fetch.php?pkg=boost1.74&arch=x32&ver=1.74.0-16&stamp=1654149541&raw=0) you see that it detects the architecture as 32bits

The debian package had to disable the build of the context library (and others that use asm) because of this wrong detection

I tested, and changing the  `<address-model>` in  https://github.com/boostorg/context/blob/develop/build/Jamfile.v2 to 32 for x32 AND setting the abi to x32 during the build allows me to build the context library properly (I didn't try more than building it). Both changes are needed otherwise it tries to build using i386 asm code and the build fails

So I guess the detection of the abi is also boggus?

**Comment by olk** [comment]
changed as adviced

**Comment by SoapGentoo** [comment]
Hi @olk
on a related note, Gentoo has been carrying a [patch](https://raw.githubusercontent.com/gentoo/gentoo/master/dev-libs/boost/files/boost-1.79.0-context-x32.patch) for x32 for ages, do you think this could be upstreamed?
