### ISSUE TITLE
s390x with Clang

### ISSUE THREAD

**Issue by klemens-morgenstern** [boostorg/context#208]
Is s390x not supported on clang on purpose? It's missing a simple target declaration from what I can see. 

It's currently a blocker on boostorg/beast#2389, though we can of course disable clang if clang is unsupported.

**Comment by olk** [comment]
I don't have access to an s390 system ... could you verify that branch develop-#208 will fix your issue.

**Comment by sdarwin** [comment]
develop-208 seems to be a major improvement.  Before, the build failed with 472 errors.  Now, only one or two errors.  https://drone.cpp.al/samd2/beast/244/1/2

```
...failed clang-linux.compile.asm bin.v2/libs/context/build/clang-linux-12/release/threading-multi/visibility-hidden/asm/make_s390x_sysv_elf_gas.o...

clang-linux.compile.asm bin.v2/libs/context/build/clang-linux-12/release/threading-multi/visibility-hidden/asm/jump_s390x_sysv_elf_gas.o

libs/context/src/asm/jump_s390x_sysv_elf_gas.S:80:2: error: unknown directive

 .machine "z10"
```

**Comment by sdarwin** [comment]
> I don't have access to an s390 system

cloud.ibm.com now has on-demand s390x virtual machines. You can launch an instance for an hour, or a day, and then delete it.

**Comment by klemens-morgenstern** [comment]
That's what we would need for the build, yes. Can you merge this and we'll see if it solves our dependency issue?

**Comment by sdarwin** [comment]
Those one or two errors seem to be solved by changing from clang-12 to clang-14.  The fix in boostorg/context was needed though.

**Comment by klemens-morgenstern** [comment]
@olk Can you merge `develop-#208` ?

**Comment by olk** [comment]
commit pushed - pleased verify

**Comment by klemens-morgenstern** [comment]
Thanks Oliver, that fixed it for us.
