### ISSUE TITLE
Document the difference between Fiber and Call/CC

### ISSUE THREAD

**Issue by naman-dixit-srib** [boostorg/context#220]
The [documentation](https://www.boost.org/doc/libs/1_81_0/libs/context/doc/html/index.html) and example code for both is near identical, and there is no explicitly documented difference between the two (or between them and `execution_context` and `coroutine`).

Could this be rectified, as it is very hard to those unfamiliar with this particular library to figure what subtle difference is there between all these alternatives?

**Comment by olk** [comment]
call/cc is based on an historic API
fiber_context is the API proposed in "P0876: fiber_context - fibers without scheduler" (C++ standardisation).
