### ISSUE TITLE
implementation doesn't match what the doc said

### ISSUE THREAD

**Issue by zhaohui0923** [boostorg/context#252]
``` cpp
// boost\libs\context\src\windows\stack_traits.cpp

BOOST_CONTEXT_DECL
std::size_t
stack_traits::default_size() BOOST_NOEXCEPT_OR_NOTHROW {
    return 128 * 1024;
}

BOOST_CONTEXT_DECL
bool
stack_traits::is_unbounded() BOOST_NOEXCEPT_OR_NOTHROW {
    return true;
}
```
for stack_traits::default_size() the doc says
> Returns a default stack size, which may be platform specific. If the stack is unbounded then the present implementation returns the maximum of 64 kB and minimum_size().

The implementation code and the doc are not matched.

**Comment by olk** [comment]
done - ty
