### ISSUE TITLE
ExecutionContext v2 Guidance

### ISSUE THREAD

**Issue by lilinjn** [boostorg/context#30]
Hi, 
I was hoping to get a some guidance about ExecutionContext v2.  Are the following statements correct?
* Execution context v2 is currently a WIP (not part of any Boost release)
* Execution context v2 is planned for Boost 1.61 (if so, is there a timeframe?)
* Execution context v2 is essentially similar in spirt to the symmetric_coro that will/may be removed from Boost.coroutine

Are there any mailing list threads that discuss the semantics of the new execution context, rationale, comparisons with the old.  

Thanks!

**Comment by olk** [comment]
- ecv2 is a new API
- ecv2 will be the standard ec of boost.context in boost-1.61
- ecv2 provides symmetric context switching
- symmetric_coroutine will remain in boost.coroutine
- boost.coroutine will be marked as deprecated soon
- boost.coroutine2 is based on ecv2 and will replace boost.coroutine
