### ISSUE TITLE
Can thread specific storage be used together with boost context?

### ISSUE THREAD

**Issue by gdochev** [boostorg/context#32]
I am testing on OSX using the simplified code below. From the main thread:

```
    int rc = pthread_key_create(&tlsKey, nullptr);
    assert(!rc);
```

From another thread:
```

    int rc = pthread_setspecific(tlsKey, this);
    assert(!rc);
    assert(this == pthread_getspecific(tlsKey)); // OK
                
    // code that switches contexts using jump_fcontext back and forth
    ...

    assert(this == pthread_getspecific(tlsKey);  // FAILURE, returns NULL
                
```

**Comment by olk** [comment]
You can use TLS together with boost.context as long as you do not migrate an execution_context, that uses TLS, from one thread to another.

**Comment by gdochev** [comment]
Thanks for the quick response! Can you elaborate what you mean by "as long as you do not migrate an execution_context, that uses TLS, from one thread to another." If you mean, storing execution_context inside TLS I do not do that.

**Comment by olk** [comment]
migrating execution_context to another thread == an execution_context is suspended in thread A and resumed in thread B

**Comment by gdochev** [comment]
I do do that but the execution_context always ends up in the same thread A, as in the code above where I call pthread_getspecific from the same thread from which I set it with pthread_setspecific.
