### ISSUE TITLE
Update documentation concerning private fcontext APIs

### ISSUE THREAD

**Issue by tobilau** [boostorg/context#33]
Although fcontext was removed from the public APIs in boost 1.61.0, it's still documented as public here: 
https://github.com/boostorg/context/blob/develop/README.md
http://www.boost.org/doc/libs/1_61_0/libs/context/doc/html/context/context.html

**Comment by olk** [comment]
thx, README.md is corrected - the mentioned context.html is build by quickbook but not linked in the official documentation
