### ISSUE TITLE
outdated doc for fcontext_t?

### ISSUE THREAD

**Issue by larryxiao** [boostorg/context#35]
[doc/fcontext.qbk](https://github.com/boostorg/context/blob/develop/doc/fcontext.qbk) or http://www.boost.org/doc/libs/1_62_0/libs/context/doc/html/context/context.html seem to be outdated for 1.62? Thanks!

Related issue: #33

**Comment by olk** [comment]
It s not part of the public oduc asyou can see here http://www.boost.org/doc/libs/1_62_0/libs/context/doc/html/index.html
