### ISSUE TITLE
apply ambiguity due to ADL with upcoming GCC 7

### ISSUE THREAD

**Issue by mickk-on-cpp** [boostorg/context#36]
It looks like Boost.Context internally implements an [`apply`](https://github.com/boostorg/context/blob/88ce079b46934b56449299f80a1b3e9f195cd966/include/boost/context/detail/apply.hpp#L52-L62) facility to invoke a functor on tuple elements.

GCC trunk has recently implemented the `std::apply` C++1z feature ([cppreference](http://en.cppreference.com/w/cpp/utility/apply)), slated for the GCC 7 release.

This means that unqualified calls inside Boost.Context ([example](https://github.com/boostorg/context/blob/88ce079b46934b56449299f80a1b3e9f195cd966/include/boost/context/execution_context_v2.hpp#L93-L97)) easily end up being ambiguous. Both `apply` are found during overload resolution, `std::apply` being found via ADL e.g. as long as an `std::tuple` specialization is involved. Because they have near identical signatures, none is preferred over the other.

**Comment by olk** [comment]
requires CXX17 defect macro in boost.config

**Comment by Flast** [comment]
IMO, no config macro is necessary. Just qualify namespace `detail::` to 4 lines, [here](https://github.com/boostorg/context/blob/2e5430fd27b963ffd72e7ee820ae81bb34c17a33/include/boost/context/execution_context_v2.hpp#L93), [also here](https://github.com/boostorg/context/blob/db244547048aac37449bcd1d3f5dd24c73cc040b/include/boost/context/execution_context_v2_void.ipp#L16), [likewise](https://github.com/boostorg/context/blob/db244547048aac37449bcd1d3f5dd24c73cc040b/include/boost/context/execution_context_v2_void.ipp#L58) and [here](https://github.com/boostorg/context/blob/db244547048aac37449bcd1d3f5dd24c73cc040b/include/boost/context/execution_context_v1.hpp#L160).

**Comment by olk** [comment]
fixed in e428581e1dfe037eb309e55ff14691f5c0d3c626
