### ISSUE TITLE
NEON registers

### ISSUE THREAD

**Issue by mofr** [boostorg/context#37]
Currently, `jump_fcontext` on ARM 32 doesn't either save or restore VFP registers (used by NEON).
It can lead to serious problems, for example, when compiler uses VFP registers during optimization.

Is it done by intention?

**Comment by olk** [comment]
It was requested by users not to preserve registers s16-s31.

**Comment by mofr** [comment]
Do you remember why it was requested? And how to deal with it in case of compiler optimizations?
I'm asking because it violates ARMv7 calling conventions.

**Comment by olk** [comment]
I was told I should remove it because it consumes cycles isn't needed. One year ago boost.context has preserved the FP-env stuff.

**Comment by olk** [comment]
I would add something like:
#if (defined(__VFP_FP__) && !defined(__SOFTFP__))
push {d8-d15}
#endif
...
#if (defined(__VFP_FP__) && !defined(__SOFTFP__))
pop {d8-d15}
#endif

**Comment by olk** [comment]
Could yout test branch fp (https://github.com/boostorg/context/tree/fp) please?
I've no access to a ARM board at the moment.

**Comment by mofr** [comment]
Unfortunately, I'm using copy-pasted version of boost. However, i've applied your changes into my version and issue has gone.
Thanks for your help and fast replies.

**Comment by olk** [comment]
Thank you too!

**Comment by mofr** [comment]
Do you plan to enable such option in future releases?
