### ISSUE TITLE
Unknown directive .cpu on aarch64 with Clang 3.8 on Android

### ISSUE THREAD

**Issue by Orphis** [boostorg/context#39]
The aarch64 files don't compile on Android with the Clang compiler because of the .cpu directive that is unsupported in version 3.8.
Support has been added to 3.9 [r265240](http://llvm.org/viewvc/llvm-project?view=revision&revision=265240)  but that version of the compiler hasn't been released with any NDK yet.

Could the offending lines be removed from all 3 arm64 elf files?
Note there's no regression test runs for aarch64 + clang in the test suite, that would explain why no one noticed before.

**Comment by olk** [comment]
> Could the offending lines be removed from all 3 arm64 elf files?

could you test and report the result please

**Comment by Orphis** [comment]
I mean, it works fine on Android if I remove them, with both GCC and Clang. 
I'm just wondering if it is required by some other toolchain for example.

**Comment by olk** [comment]
done
