### ISSUE TITLE
boost 1.63: jump_x86_64_ms_pe_gas.asm, ontop_x86_64_ms_pe_gas.asm

### ISSUE THREAD

**Issue by 2underscores-vic** [boostorg/context#43]
I use MinGW-w64 (`b2 toolset=gcc` on Windows)

```
Program received signal SIGSEGV, Segmentation fault.
jump_fcontext () at jump_x86_64_ms_pe_gas.asm:191
191         movq  %r9, (%rax)
```

The line in `jump_x86_64_ms_pe_gas.asm`

```
movq  0x110(%rsp), %rcx  /* restore hidden address of transport_t */
```

differs from the corresponding one in `jump_x86_64_ms_pe_masm.asm` which contains

```
mov rax, [rsp+0110h] ; restore hidden address of transport_t
```

**Comment by 2underscores-vic** [comment]
The same in `ontop_x86_64_ms_pe_gas.asm`

**Comment by olk** [comment]
The code for 1.64 (branch develop) has already changed - could you test the code from branch develop and verify that the fix is working, please?

**Comment by 2underscores-vic** [comment]
Replacing `%rcx` with `%rax` in 1.63 works for me.
Has anything else been changed? If so, I can try 1.64 too.

**Comment by 2underscores-vic** [comment]
I see also two `(%rax)` replaced with `0x0(%rax)` here https://github.com/boostorg/context/commit/3ea3b5cc904191fd7e5b9c98c01e85db326e094a

Is it essential?

**Comment by 2underscores-vic** [comment]
And, taking the opportunity, I'd like to inquire. Why GNU as sources on windows have `.asm` extension instead of `.S`?

**Comment by olk** [comment]
yes

**Comment by 2underscores-vic** [comment]
> The code for 1.64 (branch develop) has already changed - could you test the code from branch develop and verify that the fix is working, please?

Simple test works fine.

**Comment by olk** [comment]
ty
