### ISSUE TITLE
"rename of continuation member functions" missed a spot

### ISSUE THREAD

**Issue by Rastaban** [boostorg/context#46]
We (the MSVC++ team) do a nightly build of the latest boost sources as a compiler "Real World Code" test.  We noticed a build break after the "rename of continuation member functions" change in test/test_callcc.cpp.   Line 281 still has a c(), this should probably be changed to c.resume().

**Comment by Rastaban** [comment]
@olk could you take a look at this?  Thanks!

**Comment by olk** [comment]
done, ty
