### ISSUE TITLE
Arguments forwarding

### ISSUE THREAD

**Issue by 2underscores-vic** [boostorg/context#48]
Why `calcc()` and `continuation::resume()` pass arguments by value (`Arg ...`) instead of forwarding references (`Arg && ...`)?

**Comment by olk** [comment]
yes - see implementations of std::packaged_task

**Comment by 2underscores-vic** [comment]
What is the point? `std::thread` uses references, `std::async` uses references. `std::function` also uses values. Isn't it because `Args` are the part of signature which is a template parameter of `std::packaged_task` and `std::function`? `continuation` is not a template.

**Comment by olk** [comment]
the type (value,refernece) is forwarded to std::tuple

**Comment by 2underscores-vic** [comment]
Get it, ty
