### ISSUE TITLE
C++11? Why?

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/context#63]
Boost.Context used to work in C++03 but now claims that C++11 is required. What was the motivation for this change? It breaks Asio without offering an alternative. Can we please remove the C++11 requirement?

Please join the **#boost** chat at http://cpplang.slack.com

Thank you

**Comment by olk** [comment]
call/cc, the public API of boost.context, requires C++11 featues. call/cc is used as foundation (context switching) in boost.coroutine2 and boost.fiber. ASIO can be used boost.coroutine (pre C++11) and boost.corotuine2 (C++11 ...).
