### ISSUE TITLE
`__sanitizer_finish_switch_fiber` should be called directly after context switch

### ISSUE THREAD

**Issue by jspam** [boostorg/context#65]
According to the [AddressSanitizer API](https://code.woboq.org/gcc/libsanitizer/include/sanitizer/common_interface_defs.h.html#162):

> When code starts running on the new stack, it must call `__sanitizer_finish_switch_fiber` to finalize the switch.

Currently, Boost.Context calls `__sanitizer_finish_switch_fiber` directly *before* the context switch (instead of direc;tly *after*):

https://github.com/boostorg/context/blob/82bf54e9c2e4d21f864b6471ed3b087099d091e3/include/boost/context/continuation_ucontext.hpp#L144

This basically leads to ASan permanently being in "switching stacks" mode. Consequently, the test program from https://github.com/boostorg/coroutine/issues/30#issuecomment-325574878 crashes with an AddressSanitizer error even when using Boost.Coroutine2.

**Comment by olk** [comment]
Fix should work (tested with example segmented.cpp -> stack exhaustion).
Unfortunately ASan complains sometimes that special address ranges are already used/allocated and quits.
