### ISSUE TITLE
Missing symbols when build with vcpkg

### ISSUE THREAD

**Issue by yyzybb537** [boostorg/context#80]
The libboost_context.a missing symbols:
  make_fcontext
  jump_fcontext
  ontop_fcontext

when boost.context built by vcpkg.
I think your build script what you committed, lose the `asm` files in vcpkg.

**Comment by olk** [comment]
Wether I build boost.context with link=shared or link static, objdump -t shows the symbols of the fcontext-function contained in teh symbol table (satic and shared lib).
I don't know and use vcpkg. Is vcpkkg officially supported by boost?

**Comment by yyzybb537** [comment]
Yes, vcpkg can install boost in linux now, because boost support for vcpkg!
I think it will be popular package manager.

**Comment by yyzybb537** [comment]
The bug because when build boost-context with vcpkg. ASM files was not built, can you fix it?

**Comment by olk** [comment]
ASM files are compiled if you use b2 ... as I told you I don't use Windows and I'm unfamiliar with vcpkg.
So I've no idea why yopu get this problem ... I guess it is related how you build boost.context

**Comment by olk** [comment]
OK, tx
