### ISSUE TITLE
Possible resource leak in ucontext implementation

### ISSUE THREAD

**Issue by prograholic** [boostorg/context#99]
Hi, 

I see some strange pattern in continuation_ucontext.hpp:

**Line 295**: we construct new object using placement new operator https://github.com/boostorg/context/blob/develop/include/boost/context/continuation_ucontext.hpp#L295
**Line 302**: we throw exception https://github.com/boostorg/context/blob/develop/include/boost/context/continuation_ucontext.hpp#L302

Same pattern we can find in function `create_context2`

Do we need to destroy our object before throwing exception?

**Comment by olk** [comment]
you are right - before `throw` a `salloc.allocate(sctx)` is missing

**Comment by 2underscores-vic** [comment]
```c++
record->~capture_t();
```
?

**Comment by olk** [comment]
capture_record/fiber_capture_record do not have member variables or execute special code in the dtor

**Comment by 2underscores-vic** [comment]
Yes. But destructor is not trivial (and virtual)! I know that it 'just works' but still. Wouldn't it be better to be C++-conformant here?

**Comment by olk** [comment]
probably yes - fixed
